services:
  _defaults:
    autowire: true
    autoconfigure: true

  Idlab\Loggable\EventListener\EntityLogEntryListener: ~
  Idlab\Loggable\EventListener\TablePrefixListener: ~
  Idlab\Loggable\Service\EntitySnapshotter: ~
  Idlab\Loggable\Command\SnapshotCommand: ~
